import { chromium } from 'playwright-core';
const browser = await chromium.launch({ channel: 'chromium' });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const ce = [];
page.on('console', (m) => { if (m.type() === 'error') ce.push(m.text().slice(0, 200)); });
page.on('pageerror', (e) => ce.push('pageerror: ' + String(e).slice(0, 200)));
await page.goto('https://metall-asia.cloudplus.uz', { waitUntil: 'networkidle' });
await page.locator('input[autocomplete="username"]').first().fill('admin');
await page.locator('input[autocomplete="current-password"]').first().fill('admin');
await page.getByRole('button', { name: 'Войти' }).click();
await page.waitForTimeout(2500);
await page.getByRole('button', { name: 'CRM', exact: true }).first().click();
await page.waitForTimeout(1500);
await page.getByRole('tab', { name: 'Клиенты' }).first().click();
await page.waitForTimeout(2500);
const rows = page.locator('li button, tbody tr');
console.log('строк в списке:', await rows.count());
await page.locator('ul li').first().click();
await page.waitForTimeout(2500);
const body = await page.locator('body').innerText();
console.log('в карточке есть ИНН:', /ИНН/.test(body));
console.log('ошибки:', ce.length, ce.slice(0, 2).join(' | '));
await page.screenshot({ path: '/tmp/crm-probe/shots/card-check.png' });
await browser.close();
